### ISSUE TITLE
Rename variable names

### ISSUE THREAD

**Issue by kpestalozzi** [arillso/ansible.system#34]
https://github.com/arillso/ansible.system/blob/723cdc7adadb9a661816f8ff5df6798521de036b/roles/iptables/vars/Debian.yml#L8C47-L8C47

Should the variables not be named? 
- iptables_configuration_ipv4
- iptables_configuration_ipv6

As they are used here: https://github.com/arillso/ansible.system/blob/723cdc7adadb9a661816f8ff5df6798521de036b/roles/iptables/tasks/main.yml#L84

**Comment by sbaerlocher** [comment]
Hello @kpestalozzi,

The issue has been resolved in version 0.0.27. The problem arose due to incorrect adaptation of the variables in /vars to the new Ansible conventions for variable naming.
